language: python

install:
   - pip3 install --upgrade pip
   - pip install pytest
   - pip install stripe
   - pip install selenium
   - python -m http.server 4000 &

script: 
 pytest test.py -v --tb=short
